global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'upacip'

rule_files: []

scrape_configs:
  - job_name: 'upacip-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
