using Npgsql;

namespace Seed;

/// <summary>
/// Seeds the insurance_records table with ≥10 representative rows (AC-001).
/// Uses INSERT … ON CONFLICT (policy_number) DO NOTHING so re-runs are idempotent
/// (Edge: duplicate seed re-run).
/// </summary>
public static class InsuranceRecordSeeder
{
    // Seed namespace: patient IDs 9001–9010 reserved for dev/test seed rows.
    // GENERATED BY DEFAULT AS IDENTITY allows explicit ID inserts; patients are
    // seeded first so the FK constraint on insurance_records is satisfied.
    private sealed record SeedRow(
        int     PatientId,
        string  FirstName,
        string  LastName,
        string  ProviderName,
        string  PolicyNumber,
        DateOnly CoverageStart,
        DateOnly? CoverageEnd);

    // ≥10 entries; providers match common US insurers; BlueCross BlueShield
    // is at index 0 to guarantee AC-001 presence (AC-001)
    private static readonly IReadOnlyList<SeedRow> Rows =
    [
        new(9001, "Alice",  "Martinez", "BlueCross BlueShield", "BCBS-2024-9001",   new DateOnly(2024, 1, 1),  new DateOnly(2024, 12, 31)),
        new(9002, "Bob",    "Thompson", "Aetna",                "AETNA-2024-9002",  new DateOnly(2024, 1, 1),  new DateOnly(2024, 12, 31)),
        new(9003, "Carol",  "Jackson",  "UnitedHealthcare",     "UHC-2024-9003",    new DateOnly(2024, 1, 1),  null),
        new(9004, "David",  "Williams", "Cigna",                "CIGNA-2024-9004",  new DateOnly(2024, 3, 1),  new DateOnly(2025, 2, 28)),
        new(9005, "Eve",    "Brown",    "Humana",               "HUM-2024-9005",    new DateOnly(2024, 1, 1),  new DateOnly(2024, 12, 31)),
        new(9006, "Frank",  "Davis",    "Anthem",               "ANTHEM-2024-9006", new DateOnly(2024, 6, 1),  null),
        new(9007, "Grace",  "Miller",   "CVS Health",           "CVS-2024-9007",    new DateOnly(2024, 1, 1),  new DateOnly(2024, 12, 31)),
        new(9008, "Henry",  "Wilson",   "Molina",               "MOLINA-2024-9008", new DateOnly(2024, 1, 1),  null),
        new(9009, "Iris",   "Moore",    "WellCare",             "WC-2024-9009",     new DateOnly(2024, 1, 1),  new DateOnly(2025, 12, 31)),
        new(9010, "James",  "Taylor",   "TRICARE",              "TRIC-2024-9010",   new DateOnly(2024, 1, 1),  new DateOnly(2026, 12, 31)),
    ];

    public static async Task SeedAsync(NpgsqlConnection conn)
    {
        // Ensure a unique index exists on policy_number so that
        // ON CONFLICT (policy_number) resolves correctly — CREATE UNIQUE INDEX
        // IF NOT EXISTS is idempotent and safe to call on every run
        await using (var idxCmd = new NpgsqlCommand(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_insurance_records_policy_number " +
            "ON insurance_records (policy_number);", conn))
        {
            await idxCmd.ExecuteNonQueryAsync();
        }

        // Phase 1: seed minimal patient rows linked to the seed IDs.
        // PHI columns (email, phone, date_of_birth, insurance_provider, insurance_id)
        // are nullable bytea — NULL is valid and correct for seed data.
        // ON CONFLICT (id) DO NOTHING makes this idempotent across re-runs.
        const string patientSql =
            "INSERT INTO patients (id, first_name, last_name, created_at) " +
            "VALUES (@id, @first_name, @last_name, @created_at) " +
            "ON CONFLICT (id) DO NOTHING";

        foreach (var row in Rows)
        {
            await using var cmd = new NpgsqlCommand(patientSql, conn);
            cmd.Parameters.AddWithValue("id",         row.PatientId);
            cmd.Parameters.AddWithValue("first_name", row.FirstName);
            cmd.Parameters.AddWithValue("last_name",  row.LastName);
            cmd.Parameters.AddWithValue("created_at", DateTime.UtcNow);
            await cmd.ExecuteNonQueryAsync();
        }

        // Phase 2: seed insurance records.
        // ON CONFLICT (policy_number) DO NOTHING — idempotent re-run (Edge: duplicate seed).
        // coverage_end is nullable; DBNull.Value maps to SQL NULL.
        const string insuranceSql =
            "INSERT INTO insurance_records (patient_id, provider_name, policy_number, coverage_start, coverage_end) " +
            "VALUES (@patient_id, @provider_name, @policy_number, @coverage_start, @coverage_end) " +
            "ON CONFLICT (policy_number) DO NOTHING";

        foreach (var row in Rows)
        {
            await using var cmd = new NpgsqlCommand(insuranceSql, conn);
            cmd.Parameters.AddWithValue("patient_id",    row.PatientId);
            cmd.Parameters.AddWithValue("provider_name", row.ProviderName);
            cmd.Parameters.AddWithValue("policy_number", row.PolicyNumber);
            cmd.Parameters.AddWithValue("coverage_start", row.CoverageStart);
            cmd.Parameters.AddWithValue("coverage_end",
                row.CoverageEnd.HasValue ? (object)row.CoverageEnd.Value : DBNull.Value);
            await cmd.ExecuteNonQueryAsync();
        }
    }
}
