// <auto-generated />
using System;
using System.Text.Json;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520175254_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Data.Entities.AppointmentSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("ProviderName")
                        .HasColumnType("text")
                        .HasColumnName("provider_name");

                    b.Property<DateTime>("SlotEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("slot_end");

                    b.Property<DateTime>("SlotStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("slot_start");

                    b.HasKey("Id")
                        .HasName("pk_appointment_slots");

                    b.ToTable("appointment_slots", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("EntityId")
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentSlotId")
                        .HasColumnType("integer")
                        .HasColumnName("appointment_slot_id");

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at");

                    b.Property<int?>("NoShowRiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("no_show_risk_score");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<JsonDocument>("RiskFactors")
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_factors");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("AppointmentSlotId")
                        .HasDatabaseName("ix_bookings_appointment_slot_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_bookings_patient_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.ChunkEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chunk_text");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<int>("ExtractedRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("extracted_record_id");

                    b.HasKey("Id")
                        .HasName("pk_chunk_embeddings");

                    b.HasIndex("ExtractedRecordId")
                        .HasDatabaseName("ix_chunk_embeddings_extracted_record_id");

                    b.ToTable("chunk_embeddings", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.ClinicalDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_type");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_clinical_documents");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_clinical_documents_patient_id");

                    b.ToTable("clinical_documents", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.ExtractedRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicalDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("clinical_document_id");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.HasKey("Id")
                        .HasName("pk_extracted_records");

                    b.HasIndex("ClinicalDocumentId")
                        .HasDatabaseName("ix_extracted_records_clinical_document_id");

                    b.ToTable("extracted_records", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.InsuranceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("CoverageEnd")
                        .HasColumnType("date")
                        .HasColumnName("coverage_end");

                    b.Property<DateOnly>("CoverageStart")
                        .HasColumnType("date")
                        .HasColumnName("coverage_start");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_number");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_name");

                    b.HasKey("Id")
                        .HasName("pk_insurance_records");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_insurance_records_patient_id");

                    b.ToTable("insurance_records", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.IntakeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiefComplaint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chief_complaint");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SymptomNotes")
                        .HasColumnType("text")
                        .HasColumnName("symptom_notes");

                    b.HasKey("Id")
                        .HasName("pk_intake_records");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_intake_records_patient_id");

                    b.ToTable("intake_records", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.MedicalCodeSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("CodeSystem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_system");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ExtractedRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("extracted_record_id");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("review_status");

                    b.Property<DateTime>("SuggestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suggested_at");

                    b.HasKey("Id")
                        .HasName("pk_medical_code_suggestions");

                    b.HasIndex("ExtractedRecordId")
                        .HasDatabaseName("ix_medical_code_suggestions_extracted_record_id");

                    b.ToTable("medical_code_suggestions", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("DateOfBirth")
                        .HasColumnType("bytea")
                        .HasColumnName("date_of_birth");

                    b.Property<byte[]>("Email")
                        .HasColumnType("bytea")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<byte[]>("InsuranceId")
                        .HasColumnType("bytea")
                        .HasColumnName("insurance_id");

                    b.Property<byte[]>("InsuranceProvider")
                        .HasColumnType("bytea")
                        .HasColumnName("insurance_provider");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<byte[]>("Phone")
                        .HasColumnType("bytea")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.ReminderSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sent");

                    b.Property<string>("ReminderType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reminder_type");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.HasKey("Id")
                        .HasName("pk_reminder_schedules");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_reminder_schedules_booking_id");

                    b.ToTable("reminder_schedules", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.Booking", b =>
                {
                    b.HasOne("Api.Data.Entities.AppointmentSlot", "AppointmentSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("AppointmentSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_appointment_slots_appointment_slot_id");

                    b.HasOne("Api.Data.Entities.Patient", "Patient")
                        .WithMany("Bookings")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_patients_patient_id");

                    b.Navigation("AppointmentSlot");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Api.Data.Entities.ChunkEmbedding", b =>
                {
                    b.HasOne("Api.Data.Entities.ExtractedRecord", "ExtractedRecord")
                        .WithMany("ChunkEmbeddings")
                        .HasForeignKey("ExtractedRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chunk_embeddings_extracted_records_extracted_record_id");

                    b.Navigation("ExtractedRecord");
                });

            modelBuilder.Entity("Api.Data.Entities.ClinicalDocument", b =>
                {
                    b.HasOne("Api.Data.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clinical_documents_patients_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Api.Data.Entities.ExtractedRecord", b =>
                {
                    b.HasOne("Api.Data.Entities.ClinicalDocument", "ClinicalDocument")
                        .WithMany("ExtractedRecords")
                        .HasForeignKey("ClinicalDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extracted_records_clinical_documents_clinical_document_id");

                    b.Navigation("ClinicalDocument");
                });

            modelBuilder.Entity("Api.Data.Entities.InsuranceRecord", b =>
                {
                    b.HasOne("Api.Data.Entities.Patient", "Patient")
                        .WithMany("InsuranceRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_insurance_records_patients_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Api.Data.Entities.IntakeRecord", b =>
                {
                    b.HasOne("Api.Data.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_intake_records_patients_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Api.Data.Entities.MedicalCodeSuggestion", b =>
                {
                    b.HasOne("Api.Data.Entities.ExtractedRecord", "ExtractedRecord")
                        .WithMany("MedicalCodeSuggestions")
                        .HasForeignKey("ExtractedRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medical_code_suggestions_extracted_records_extracted_record");

                    b.Navigation("ExtractedRecord");
                });

            modelBuilder.Entity("Api.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("Api.Data.Entities.ReminderSchedule", b =>
                {
                    b.HasOne("Api.Data.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reminder_schedules_bookings_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Api.Data.Entities.AppointmentSlot", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Api.Data.Entities.ClinicalDocument", b =>
                {
                    b.Navigation("ExtractedRecords");
                });

            modelBuilder.Entity("Api.Data.Entities.ExtractedRecord", b =>
                {
                    b.Navigation("ChunkEmbeddings");

                    b.Navigation("MedicalCodeSuggestions");
                });

            modelBuilder.Entity("Api.Data.Entities.Patient", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("InsuranceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
